[build]
  command = "npm i --legacy-peer-deps && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://secure-brushlands-73777-bf5e5d7d211f.herokuapp.com/api/:splat"
  status = 200
  force = true

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"